# Generated by Django 5.2.7 on 2025-10-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('total_miles_driven', models.FloatField(default=0.0)),
                ('total_mileage_today', models.FloatField(default=0.0)),
                ('trailer_or_plate', models.CharField(blank=True, max_length=100, null=True)),
                ('carrier_name', models.CharField(blank=True, max_length=255, null=True)),
                ('main_office_address', models.CharField(blank=True, max_length=255, null=True)),
                ('home_terminal_address', models.CharField(blank=True, max_length=255, null=True)),
                ('manifest_number', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_and_commodity', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('total_driving_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_on_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_off_duty_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('total_sleeper_hours', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty', 'On Duty (Not Driving)')], max_length=20)),
                ('start_hour', models.PositiveSmallIntegerField()),
                ('end_hour', models.PositiveSmallIntegerField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('location_name', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
