# Generated by Django 5.2.7 on 2025-10-25 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='trips.trip'),
        ),
        migrations.AddField(
            model_name='logentry',
            name='daily_log',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='logs.dailylog'),
        ),
    ]
